from mysql.connector import connect, cursor
from mysql.connector.errors import ProgrammingError
from mysql.connector.errors import InterfaceError
     


def connect_to_db(db_name):
    username = "root"
    passwd = "coderslab"
    hostname = "127.0.0.1"
    #db_name = "exercises_db"
    
    try: 
        cnx = connect(user = username, password = passwd, host = hostname, database = db_name)
        cnx.autocommit = True #<--------------------------
        cursor = cnx.cursor()
        cursor.execute(sql_create_db)
        # cnx.commit() <--------------------------
        cursor.close()
        cnx.close()        
        print("Połączenie gotowe")
        
        
    except ProgrammingError as e:        #except ProgramingError as e:
        print(e) #"Nieudane połączenie")# print(e)
    except InterfaceError:
        print("Zła nazwa hosta")    
    return(cnx)



sql_create_db = """create table Kino(id int not null auto_increment,
                             name varchar (255) character set utf8,
                              adress varchar (255) character set utf8,
                               primary key (id));""" 
 

#connect_to_db("cinemas_db")

sql_create_db = """create table Film(id int not null auto_increment,
                             name varchar (255) character set utf8,
                              opis varchar (255) character set utf8,
                               primary key (id));""" 
 


#connect_to_db("cinemas_db")

sql_create_db = """create table Bilet(id int not null auto_increment,
                                 ilosc tinyint not null,
                                 cena decimal(3,2) not null,
                               primary key (id));""" 

#connect_to_db("cinemas_db")

sql_create_db = """create table Platnosc(id int not null auto_increment,
                                 typ varchar (255) character set utf8 not null,
                                 data date not null,
                               primary key (id));""" 
connect_to_db("cinemas_db")